IF
	!Dead("L#DENDJELION")
	Global("C0HolvirDendjelionFight","GLOBAL",1)
THEN
  RESPONSE #100
	SetInterrupt(FALSE)
	LeaveParty()
	Attack("L#DENDJELION")
	SetInterrupt(TRUE)
END

IF
	InMyArea(Player1)
	Dead("L#DENDJELION")
	Global("C0HolvirDendjelionFight","GLOBAL",1)
THEN
  RESPONSE #100
	SetInterrupt(FALSE)
	SetGlobal("C0HolvirDendjelionFight","GLOBAL",2)
	StartDialogueNoSet(Player1)
	SetInterrupt(TRUE)
END